### ISSUE TITLE
Colour Settings not sticking

### ISSUE THREAD

**Issue by kackburt** [lynchdean/DeansSimpleWatchFace#4] opened 2024-06-06 08:40 UTC
After the latest update (must be v1.2.6), the colour settings are not sticking for me.
When hitting "Save" in the Garmin Connect IQ app, the colours are correct (f.e. white text, white icons), but as soon as I move up or down (glances/widgets) and back to the watch face, the colours have the default colouring (white text, grey icons) again.

- Device: Garmin Forerunner 965
- Garmin OS Version: 19.18
- Dean's Simple Watch Face Version: 1.2.6

**Comment by lynchdean** [comment] 2024-06-06 13:09
> After the latest update (must be v1.2.6), the colour settings are not sticking for me.
> 
> When hitting "Save" in the Garmin Connect IQ app, the colours are correct (f.e. white text, white icons), but as soon as I move up or down (glances/widgets) and back to the watch face, the colours have the default colouring (white text, grey icons) again.
> 
> 
> 
> - Device: Garmin Forerunner 965
> 
> - Garmin OS Version: 19.18
> 
> - Dean's Simple Watch Face Version: 1.2.6
> 
>   

Hi, thanks for raising the issue and providing details. I can confirm that this is not an isolated issue and I will look into it as soon as I get a chance. 

Apologies, there have been a few issues with the watch face since the last feature update (1.2.X) that I regrettably haven't got on top of.

**Comment by lynchdean** [comment] 2024-06-06 15:11
I have fixed the issue in my test build on my watch but at the expense of making the IQ issue more prevalent again. I'm going to hold off on uploading this until the IQ issue is 100% resolved. Unfortunately it might be a few days before I have the time to properly tackle this.

**Comment by lynchdean** [comment] 2024-08-08 14:33
This fix has been now been pushed along with the IQ error fix.

**Closed by lynchdean** 2024-08-08 14:33 UTC
